import { SlashCommand } from "./types.js";
import { formatFocusedHelp } from "../help-topics.js";

export const HELP_LINES = [
  "",
  "【轻灵 Slash Commands】",
  "-----------------------------------------",
  "/help, /?               - 显示此帮助信息",
  "/init [--force]         - 生成轻灵本地项目指南",
  "/model [list|use <p>|m] - 查看/列出预设/切换模型或 Provider",
  "/plan [on|off|status|..] - Plan Mode（只读规划，禁写工具）",
  "/mode [status|cycle]    - 循环 Agent、Plan 与 Always Agree（Shift+Tab）",
  "/expand [on|off|status]  - 切换长工具输出展开（同 Ctrl+O）",
  "/plan [description]     - 创建普通会话计划请求",
  "/usage, /cost, /stats   - 查看 provider 官方 token usage",
  "/diff                   - 查看当前 Git 变更摘要",
  "/copy [N]               - 复制最近第 N 条 assistant 回复",
  "/rewind, /undo          - 查看可恢复会话点",
  "/skill [list|search <query>|name] - 列出、搜索或读取本地技能",
  "/sessions               - 查看最近保存的会话快照",
  "/resume [session|latest] - 恢复最近一次或指定会话",
  "/checkpoint [name] [--force], /检查点 - 保存当前会话为本地恢复检查点",
  "/clear, /reset          - 清空当前对话上下文",
  "/compact                - 手动触发上下文压缩",
  "/goal [condition|clear] - 设定、查询或清除当前 session 的目标条件",
  "/goal daemon            - 查询 daemon runner 的 goal 状态",
  "/goal daemon clear      - 清理 daemon runner 的 goal",
  "/goal daemon <condition> - 将 goal 交由 qlingd 在后台持续推进",
  "/loop [interval] [prompt] - 在当前 session 内周期性重跑 prompt",
  "/loop daemon [interval] [prompt] - 创建 daemon-backed durable loop",
  "/tasks [cancel <id>|clear] - 查看或取消当前 session 的 loop 任务",
  "/tasks daemon [cancel <id>|clear] - 查看或取消 daemon runner 的 loop 任务",
  "/agents, /代理         - 子代理角色说明 + 本地 mission 分组（roles|missions）",
  "/mission, /使命        - 查看或控制本地 mission",
  "/permissions [status|allow|deny|ask] - 查看或切换工具权限默认策略",
  "/permissions explain <tool> - 解释指定工具的本地权限决策",
  "/statusline [on|off]   - 查看或切换 prompt 前本地状态线",
  "/recap [count], /回顾   - 查看当前本地会话回顾",
  "/privacy, /隐私         - 查看本地数据留存路径与边界说明",
  "/shortcuts, /快捷键     - 查看 TUI 输入快捷键",
  "/queue [clear], /队列 [清空] - TUI 中即时查看或清空 pending 输入队列",
  "/export, /导出          - 将当前会话导出为本地 Markdown",
  "/exports [count], /导出列表 - 查看本地 Markdown 导出列表",
  "/memory [count], /记忆   - 查看本地持久化记忆索引",
  "/memory search <query>   - 搜索本地持久化记忆并显示匹配路径",
  "/memory sources          - 查看本地上下文记忆来源与边界",
  "/memory practices [count] - 查看本地蒸馏实践摘要",
  "/memory graph [count]   - 查看本地知识图谱节点摘要",
  "/memory show <id>       - 查看指定本地记忆详情",
  "/dream [count], /沉淀    - 从当前会话沉淀本地记忆",
  "/distill [count], /蒸馏  - 查看本地蒸馏实践摘要",
  "/storage, /存储         - 查看本地数据存储占用",
  "/repomap [path] [limit] - 扫描项目文件并生成符号地图（Repo Map）",
  "/verify status|set <cmd>|clear|run - 配置与运行构建/测试验证与自动自愈",
  "/mcp, /外部工具         - 查看本地 MCP server 配置摘要",
  "/hooks, /钩子           - 查看本地 hooks/guard 配置摘要",
  "/doctor, /诊断          - 运行本地稳定性与数据留存诊断",
  "/context, /上下文       - 查看上下文占用与本地留存路径",
  "/config                 - 查看当前生效配置",
  "/status                 - 查看会话状态与 Token 统计",
  "/dashboard              - 获取观测控制台链接",
  "-----------------------------------------",
  "提示: 输入 /help <topic> 查看聚焦帮助；帮助与纠错均在本地完成，不调用模型。",
  "安全: API key 推荐放在系统用户环境变量；setup 不会写入 .env。",
  "",
];

export const helpCommand: SlashCommand = {
  name: "/help",
  aliases: ["/?"],
  description: "显示可用指令列表",
  usage: "/help [topic]",
  execute: async (args, context) => {
    const lines = args.length ? formatFocusedHelp(args.join(" "), { surface: "slash" }) : HELP_LINES;
    for (const line of lines) {
      context.writeLine(line);
    }
  },
};
