import { SlashCommand } from "./types.js";
import { formatFocusedHelp } from "../help-topics.js";

export const HELP_LINES = [
  "",
  "【轻灵 Slash Commands】",
  "-----------------------------------------",
  "/help, /?               - 显示此帮助信息",
  "/init [--force]         - 生成轻灵本地项目指南",
  "/model [list|use <p>|m] - 模型切换器（默认）或直切预设",
  "/plan [on|off|list|approve|desc] - Plan；list 为计划文件切换器",
  "/mode [status|cycle|normal|plan|auto] - 模式切换器；Shift+Tab 循环",
  "/always-approve         - 直切 auto（工具默认免确认）",
  "/theme · /sandbox · /skill · /permissions · /sessions - 均为切换器（无参打开）",
  "/expand [on|off|status]  - 切换长工具输出展开（同 Ctrl+O）",
  "/usage, /cost, /stats   - 查看 provider 官方 token usage",
  "/diff                   - 查看当前 Git 变更摘要",
  "/copy [N]               - 复制最近第 N 条 assistant 回复",
  "/rewind [n], /undo      - 回退最近 n 个用户轮（默认 1）并保存",
  "/fork [name]            - 分叉当前对话为新 session",
  "/skill [list|search|name]  - 技能切换器（键入可含空格）· /name 亦可直达 skill",
  "/sessions [pick|list]   - 会话舰队（默认）或列表；Ctrl+\\ · /dashboard 同效",
  "/resume [pick|latest|id]- 无参/pick 打开切换器；latest 或 id 直接恢复",
  "/expand [last|on|off]   - 工具输出折叠；last 重放最近一次",
  "/checkpoint [name] [--force], /检查点 - 保存当前会话为本地恢复检查点",
  "/clear, /reset          - 清空当前对话上下文",
  "/compact [n] [主题]     - 压缩上下文；n=保留最近条数，可带主题焦点",
  "/goal [condition|clear] - 设定、查询或清除当前 session 的目标条件",
  "/goal daemon            - 查询 daemon runner 的 goal 状态",
  "/goal daemon clear      - 清理 daemon runner 的 goal",
  "/goal daemon <condition> - 将 goal 交由 qlingd 在后台持续推进",
  "/loop [interval] [prompt] - 在当前 session 内周期性重跑 prompt",
  "/loop daemon [interval] [prompt] - 创建 daemon-backed durable loop",
  "/tasks [list|wait|kill|cancel|clear] - shell task_id + session loop",
  "/tasks daemon [cancel <id>|clear] - daemon runner 的 loop 任务",
  "/agents, /代理         - 子代理角色说明 + 本地 mission 分组（roles|missions）",
  "/mission, /使命        - 查看或控制本地 mission",
  "/permissions [status|pipeline|grants|forget|allow|deny|ask|explain] - 权限流水线与 mode",
  "/sandbox [workspace|read-only|strict|roots|off] - 路径沙箱 profile",
  "/theme [bamboo|night|mono] - TUI 主题包",
  "/statusline [on|off]   - 查看或切换 prompt 前本地状态线",
  "/recap [count], /回顾   - 查看当前本地会话回顾",
  "/privacy, /隐私         - 查看本地数据留存路径与边界说明",
  "/shortcuts, /快捷键     - 查看 TUI 输入快捷键",
  "/queue [clear], /队列 [清空] - TUI 中即时查看或清空 pending 输入队列",
  "/export, /导出          - 将当前会话导出为本地 Markdown",
  "/exports [count], /导出列表 - 查看本地 Markdown 导出列表",
  "/memory [count], /记忆   - 查看本地持久化记忆索引",
  "/memory search <query>   - 搜索本地持久化记忆并显示匹配路径",
  "/memory sources          - 查看本地上下文记忆来源与边界",
  "/memory practices [count] - 查看本地蒸馏实践摘要",
  "/memory graph [count]   - 查看本地知识图谱节点摘要",
  "/memory show <id>       - 查看指定本地记忆详情",
  "/dream [count], /沉淀    - 从当前会话沉淀本地记忆",
  "/distill [count], /蒸馏  - 查看本地蒸馏实践摘要",
  "/storage, /存储         - 查看本地数据存储占用",
  "/repomap [path] [limit] - 扫描项目文件并生成符号地图（Repo Map）",
  "/verify status|set <cmd>|clear|run - 配置与运行构建/测试验证与自动自愈",
  "/mcp, /外部工具         - 查看本地 MCP server 配置摘要",
  "/hooks, /钩子           - 查看本地 hooks/guard 配置摘要",
  "/doctor, /诊断          - 运行本地稳定性与数据留存诊断",
  "/context, /上下文       - 上下文占用分类 system/messages/tools/free",
  "/config                 - 查看当前生效配置",
  "/status                 - 查看会话状态与 Token 统计",
  "/dashboard [tui|web]    - 会话舰队（默认）或 Web 任务台链接",
  "-----------------------------------------",
  "提示: 输入 /help <topic> 查看聚焦帮助；帮助与纠错均在本地完成，不调用模型。",
  "安全: API key 推荐放在系统用户环境变量；setup 不会写入 .env。",
  "",
];

export const helpCommand: SlashCommand = {
  name: "/help",
  aliases: ["/?"],
  description: "显示可用指令列表",
  usage: "/help [topic]",
  execute: async (args, context) => {
    const lines = args.length ? formatFocusedHelp(args.join(" "), { surface: "slash" }) : HELP_LINES;
    for (const line of lines) {
      context.writeLine(line);
    }
  },
};
